//! The portal register: which portal rooms a bridge has built, and which of
//! them the Sensor is inside (ticket #105, ADR 0024).
//!
//! # The defect this exists for
//!
//! A bridge builds a portal room **lazily**, when a conversation becomes
//! active — not once, at login. Measured on the reference deployment, one
//! WhatsApp account produced eighteen portal rooms between 04:54 and 13:24 as
//! people wrote, and the Sensor was in exactly one of them: the one somebody
//! had invited it into by hand. mautrix invites *the user* into a portal it
//! creates and nothing else; there is no bridge setting that would invite a
//! third account, and `SENSOR_ALLOWED_INVITERS` only settles what the Sensor
//! *accepts* once somebody has asked.
//!
//! So the deployment went deaf on seventeen conversations while every
//! component reported itself healthy, and the deafness **grows on its own**:
//! a fix that invited the Sensor into the rooms that exist when a network is
//! connected would have been correct for an hour and wrong by the evening.
//! Whatever closes this has to react to portal creation, continuously.
//!
//! # What this module is, and what it deliberately is not
//!
//! It is the **mechanism**. The policy — which conversations Twalk may watch
//! — is the user's, and it is expressed one conversation at a time (#143).
//! Those eighteen rooms held roughly 1,300 memberships, a two-person
//! conversation with a family member and a 246-member association under the
//! same mechanism; inviting the Sensor into all of them by default would
//! publish those people's messages, which is the decision #122 is about. So
//! **the default is to observe nothing**: this module discovers portal rooms
//! and offers them, and the Sensor enters one only when the user says so.
//!
//! It is also **not a store**. Every read asks the homeserver, and the answer
//! to "is the Sensor observing this conversation?" is the Sensor's own
//! membership event, not a row the Gateway wrote. Nothing here can drift from
//! the system it describes, a reconnection that rebuilds every portal is
//! simply the next read, and there is no second record for a replay to
//! disagree with.
//!
//! # Whose credential does the asking
//!
//! A portal room's members are the user, the bridge bot and the network
//! ghosts. The Gateway holds no Matrix access token of the user's (ADR 0011)
//! and will not start holding one, so the account it acts as is **the bridge
//! bot**, through the appservice token the operator already configured for
//! that bridge (`GATEWAY_BRIDGE_<ID>_AS_TOKEN`, ticket #56). Until now the
//! Gateway held that token only to *verify* the bridge's status pushes; this
//! module is the first thing that acts with it, which is the change of
//! posture a reviewer should weigh (`docs/architecture/security-model.md`).
//!
//! The bot is the right asker for three reasons: it is in every portal of its
//! own bridge and in nobody else's rooms, it created them and therefore can
//! invite, and the credential exists already — nothing new is stored and no
//! new secret is minted. The token is a Matrix credential and nothing more:
//! the code below speaks the ordinary client-server API with it and asks for
//! nothing an appservice alone can do — except the one thing it must, below.
//!
//! **Acting as the bot takes `?user_id=`, and #105 did not send it.** This
//! module's first version said the register spoke "as the token's own default
//! identity", believing that identity to be the bot. It is not. An appservice
//! token used with no `?user_id=` acts as the registration's
//! `sender_localpart`, and a registration generated by a bridge has a random
//! localpart that is joined to nothing and never will be. So on the reference
//! deployment the register read 32 portal rooms as
//! `@jaay9HZczkCQNHiIzolLOrvm99Cby90B:twalk.localhost`, found zero, and said
//! zero (#171). The decision was always *act as the bridge's own bot*; the
//! mechanism did not carry it out.
//!
//! Which is why the bot's Matrix ID is **configuration**
//! (`GATEWAY_BRIDGE_<ID>_BOT_USER_ID`) and not a string this module builds. A
//! bot's localpart is its own `bridge.bot_username`, so `@{bridge_id}bot:` is
//! a convention and not a fact — the same refusal ADR 0018 made about the
//! owner's network ghosts, for the same reason. The narrowing that replaces
//! the false one is stronger and the code can enforce it: `?user_id=` names
//! **only** the bot the operator configured — never a ghost, never a value
//! derived from a request, never one assembled from a bridge id — and an
//! observation request is still resolved against a live register first, so a
//! room id can never send this credential somewhere its bot is not already.
//!
//! A bridge the operator gave no token for is **not** silently skipped. It is
//! reported as unreadable, with the variable that would open it, because "the
//! Sensor is outside 17 of your 18 conversations" must never quietly mean
//! "…of the 18 I could see". And a bridge that *was* read says **which
//! account it asked as and how many rooms that account is in**, because #171
//! was a defect whose whole symptom was a zero indistinguishable from the
//! truth.
//!
//! # The three states, and why `invited` is one of them
//!
//! A portal is `observing`, `invited` or `absent`. `invited` is not an
//! implementation detail on the way to `observing`: it is what a deployment
//! looks like when `SENSOR_ALLOWED_INVITERS` does not name the bridge bot.
//! The invitation lands, the Sensor ignores it, and without this state the
//! symptom would again be silence that nothing accounts for. A portal stuck
//! at `invited` names its own cause.
//!
//! # What a portal says about itself, and what it does not decide
//!
//! Since #143 the answer carries the **network's own identifier** for the
//! conversation ([`Portal::network_conversation_id`]) beside its name and its
//! member count: the `channel.id` the bridge wrote into `m.bridge`, copied
//! and never read. It is here because the screen that asks the user to decide
//! one conversation at a time has to be able to say *which* conversation, and
//! a WhatsApp community arrives as a parent, an announcement group and
//! subgroups carrying near-identical names — three rows called `XVDSI` that a
//! name and a headcount cannot tell apart. The suffix of that id
//! distinguishes a person from a group without guessing, which is why it is
//! passed through rather than interpreted: the register projects the
//! homeserver, and a kind computed here could contradict, in the same answer,
//! the bridge's own id it was computed from.

use std::collections::{BTreeMap, BTreeSet};
use std::sync::Arc;

use futures::StreamExt;
use serde::Deserialize;
use tracing::{debug, info, warn};

use crate::metrics::Metrics;

/// How long the Gateway waits for the homeserver on one portal call. Shorter
/// than bootstrap's registration timeout: a register read is many calls and a
/// slow one must not hold the whole list.
const HOMESERVER_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(10);

/// How many rooms of one bridge are read at a time. The homeserver is on the
/// deployment's own network and a personal account has tens of portals, so
/// this is about not opening ninety sockets at once rather than about speed.
const ROOM_READ_CONCURRENCY: usize = 6;

/// The most rooms one observation request may name. Higher than bootstrap's
/// cap, because that one is a list a user ticks by hand on screen 3d and this
/// one is what a "watch this whole network" control (#143) sends in one
/// gesture — and still bounded, so one request cannot become an unbounded
/// number of invitations.
pub const MAX_ROOMS_PER_REQUEST: usize = 256;

/// Where a member count stops being a list and becomes a **crowd** — a
/// conversation the user must acknowledge the size of before observing it
/// (#143) — when the operator sets no threshold.
///
/// Measured, not tasted: on the reference account the largest group whose
/// members a user could name is eleven (`Échecs en Yvelines`, the
/// announcement group), and the smallest that is unmistakably a crowd is
/// seventy-three (`RAG I Infos`). Twenty sits between them, on the side of
/// asking too often rather than too rarely.
///
/// It lives here and not on screen because the register applies it too: a
/// replaced room's successor is followed under it and returned to the
/// chooser above it (ADR 0029, #255), and a threshold that applied only at
/// the moment of ticking would be one it suffices to wait out. The Companion
/// reads the served value (`crowd_threshold`) and holds no number of its own.
pub const DEFAULT_CROWD_THRESHOLD: u64 = 20;

/// How often the background refresher re-reads the register to keep the
/// gauges honest, when the operator sets no interval. The API's own read is
/// always live; this only decides how stale `/metrics` may be, so it is
/// deliberately unhurried — the register costs one call per portal room.
pub const DEFAULT_REFRESH_SECONDS: u64 = 300;

/// Where the Sensor stands in one portal room.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Observation {
    /// The Sensor has joined: this conversation reaches the bus.
    Observing,
    /// The Sensor was invited and has not joined. Normally a moment; when it
    /// lasts, the Sensor is refusing the inviter — see the module docs.
    Invited,
    /// The Sensor is not in the room and has not been asked to be. The
    /// default for every portal a bridge builds.
    Absent,
    /// The conversation's room was replaced (`m.room.tombstone`) while the
    /// Sensor was in it, and the Sensor is not in the successor (ADR 0029,
    /// issue #253). A decision is on record about this conversation and has
    /// silently stopped meaning anything — which is why this is its own state
    /// and not `absent`: the same argument ADR 0024 made for `invited`,
    /// without it the symptom is a silence nothing accounts for.
    Moved,
}

impl Observation {
    /// The stable label, in the API, in the logs and in the metric.
    pub fn label(&self) -> &'static str {
        match self {
            Observation::Observing => "observing",
            Observation::Invited => "invited",
            Observation::Absent => "absent",
            Observation::Moved => "moved",
        }
    }

    /// Whether the Sensor stands in the room at all — joined or invited —
    /// which is what a replaced room hands on to its successor.
    fn sensor_is_in_the_room(&self) -> bool {
        matches!(self, Observation::Observing | Observation::Invited)
    }
}

/// One portal room, as the homeserver answers about it right now.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Portal {
    pub room_id: String,
    /// The bridge instance whose bot is in this room (`GATEWAY_BRIDGES`).
    pub bridge_id: String,
    /// The network the user experiences, from the room's own `m.bridge`
    /// marker when it names one this version knows, and from the bridge's
    /// configuration otherwise.
    pub network: String,
    /// The room's name — for a one-to-one portal, the contact's; for a group,
    /// the group's. Read through and never written down.
    pub name: Option<String>,
    /// **The network's own identifier for this conversation**, exactly as the
    /// bridge wrote it into the room's `m.bridge` marker (`channel.id`), and
    /// `None` where the bridge wrote none.
    ///
    /// Passed through untouched: not parsed, not normalised, not invented
    /// here. It is the bridge's value and it is the network's vocabulary —
    /// `231546065817642@lid` and `33612345678@s.whatsapp.net` are how
    /// WhatsApp addresses one person, `120363201980306353@g.us` how it
    /// addresses a group — so its *suffix* is the only non-guessing answer to
    /// "what kind of conversation is this?".
    ///
    /// Reading that suffix is the **Companion's** job and not this module's
    /// (#143): a kind is a thing to render, the register is a projection of
    /// the homeserver, and a Gateway that classified would be a Gateway whose
    /// classification could disagree with the bridge's own id in the same
    /// answer. So nothing here looks at it, and `network_of_protocol` — which
    /// does interpret a value — stays on `protocol.id`, where the vocabulary
    /// is mautrix's and finite.
    pub network_conversation_id: Option<String>,
    /// How many people are in the conversation: joined members, **excluding**
    /// the bridge bot and the Sensor. Excluding them is what keeps the number
    /// the user reads from changing when they decide to observe the room.
    pub members: u64,
    pub observation: Observation,
    /// The room this conversation lived in before it was replaced, when it
    /// was: the immediate predecessor's id, out of the successor's own
    /// `m.room.create` or the predecessor's `m.room.tombstone`. The dead room
    /// is not a row of its own — a moved conversation appears **once**, here
    /// (ADR 0029).
    pub moved_from: Option<String>,
    /// `Some(why)` when this row stands for a successor the register could
    /// not read — the bridge bot is not in it — and was built from the
    /// tombstone that names it. A tombstone that points into the dark is a
    /// fact, and not a reason to fold the conversation into nothing.
    pub unreadable: Option<String>,
    /// The successor this room's `m.room.tombstone` names, when the room is
    /// dead. Read from the homeserver, consumed by [`fold_tombstones`], never
    /// part of the answer: the answer is keyed on the room that is alive.
    pub replaced_by: Option<String>,
}

/// Follows every `m.room.tombstone` to the room that is alive, so that a
/// conversation whose room was replaced appears **once**, at its successor
/// (ADR 0029, issue #253).
///
/// A dead room stops being a row. What it hands on to its successor is the
/// one fact the successor cannot know by itself: whether the Sensor was in
/// the conversation before it moved. A successor the Sensor is not in
/// becomes [`Observation::Moved`] when the predecessor had the Sensor —
/// a decision on record, silently voided — and stays what it is otherwise: a
/// conversation nobody chose moves and is still `absent`. A chain of
/// replacements resolves to its last room, each hop bounded so a cycle a
/// misbehaving server produced cannot spin this for ever.
///
/// A successor that is not among the readable portals is still answered: a
/// row built from the tombstone, carrying the predecessor's name, network and
/// bridge, marked `unreadable` and `moved` when the Sensor was in the
/// predecessor. The alternative, folding the conversation into nothing, is
/// exactly the silence this state exists to break. `bot_rooms` — every room
/// any bridge bot is in — tells the two reasons apart, because they are two
/// situations: a successor the bot is in but has not marked as a portal yet
/// (the ordinary window right after a migration, since a room upgrade copies
/// no custom state) and a successor the bot is not in at all.
///
/// Two dead rooms may name one successor; the fold is deterministic (rooms
/// are walked in id order) and the Sensor's presence in *any* of them is what
/// carries — a decision on record in one of two predecessors is still a
/// decision on record.
pub fn fold_tombstones(portals: Vec<Portal>, bot_rooms: &BTreeSet<String>) -> Vec<Portal> {
    /// How many replacements one conversation may have been through before
    /// the walk stops where it stands. Far above anything real — a room is
    /// upgraded when a room version changes, a handful of times in a
    /// homeserver's life — and small enough that a cycle a misbehaving server
    /// produced costs a few iterations rather than a hung register.
    const MAX_HOPS: usize = 32;
    let by_room: BTreeMap<String, Portal> = portals
        .into_iter()
        .map(|portal| (portal.room_id.clone(), portal))
        .collect();
    let mut folded: BTreeMap<String, Portal> = BTreeMap::new();
    for (room_id, portal) in &by_room {
        if portal.replaced_by.is_none() {
            // Alive: a row, unless a dead room's fold already placed one here
            // — in which case the dead room's contribution (moved_from, and
            // the Sensor's former presence) is kept and the live reading wins
            // for everything the live room knows better.
            let row = folded.remove(room_id).map_or_else(
                || portal.clone(),
                |from_tombstone| Portal {
                    moved_from: from_tombstone
                        .moved_from
                        .or_else(|| portal.moved_from.clone()),
                    observation: if portal.observation.sensor_is_in_the_room() {
                        portal.observation
                    } else {
                        from_tombstone.observation
                    },
                    unreadable: None,
                    ..portal.clone()
                },
            );
            folded.insert(room_id.clone(), row);
            continue;
        }
        // Dead: walk to the last room the chain names.
        let mut predecessor = portal;
        let mut hops = 0;
        let successor_id = loop {
            let Some(next) = predecessor.replaced_by.as_deref() else {
                break predecessor.room_id.clone();
            };
            hops += 1;
            if hops > MAX_HOPS {
                warn!(
                    room = %portal.room_id,
                    "a tombstone chain longer than {MAX_HOPS} hops; stopping at the last readable room"
                );
                break predecessor.room_id.clone();
            }
            match by_room.get(next) {
                Some(further) => predecessor = further,
                // The successor is not a room the bot is in: the chain ends
                // in the dark, at a room we know only by name.
                None => break next.to_owned(),
            }
        };
        let sensor_was_in_it = portal.observation.sensor_is_in_the_room();
        let readable_successor = by_room.get(&successor_id);
        let row = folded
            .entry(successor_id.clone())
            .or_insert_with(|| match readable_successor {
                Some(alive) => alive.clone(),
                None => Portal {
                    room_id: successor_id.clone(),
                    bridge_id: predecessor.bridge_id.clone(),
                    network: predecessor.network.clone(),
                    name: predecessor.name.clone(),
                    network_conversation_id: predecessor.network_conversation_id.clone(),
                    members: predecessor.members,
                    observation: Observation::Absent,
                    moved_from: None,
                    unreadable: Some(if bot_rooms.contains(&successor_id) {
                        "this conversation's room was replaced, and the bridge is in the new \
                         room but has not marked it as a portal yet: the name and count are \
                         the old room's until it does"
                            .to_owned()
                    } else {
                        "this conversation's room was replaced, and the bridge bot is not in \
                         the new room, so it cannot be read: what is known about it is what \
                         the old room's tombstone says"
                            .to_owned()
                    }),
                    replaced_by: None,
                },
            });
        // The immediate predecessor of the final room is the one to name;
        // for the room in the dark that is whoever pointed at it.
        if row.moved_from.is_none() {
            row.moved_from = Some(predecessor.room_id.clone());
        }
        if sensor_was_in_it && !row.observation.sensor_is_in_the_room() {
            row.observation = Observation::Moved;
        }
    }
    folded.into_values().collect()
}

/// Whether one configured bridge could be read, and why not when it could
/// not. Always present for every bridge in `GATEWAY_BRIDGES`, so a count of
/// portals is never mistaken for a count of conversations.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BridgeReading {
    pub bridge_id: String,
    pub network: String,
    /// `None` when the bridge was read. `Some(detail)` names what stopped it,
    /// in the operator's words.
    pub unreadable: Option<String>,
    /// **The account the register actually spoke as**, as the homeserver
    /// itself names it: the configured bot, or — when none is configured —
    /// whatever `whoami` says the token is. `None` only when the bridge could
    /// not be read at all.
    ///
    /// Here because of #171. `absent: 0, unreadable: 0` said two entirely
    /// different things and a deployment could not tell them apart: *your
    /// bridges have built no conversations yet*, which is the truth on a
    /// fresh deployment, and *the register asked an account that is in no
    /// rooms*, which is a defect. It answered the second for a deployment
    /// with 32 portal rooms. An unreadable bridge was reported; a bridge read
    /// as the wrong account was indistinguishable from a quiet, correct zero,
    /// which is exactly what ADR 0024 was written against.
    pub asked_as: Option<String>,
    /// How many rooms that account is joined to — **every** room, not only
    /// the ones carrying an `m.bridge` marker.
    ///
    /// The other half of the pair above: `joined_rooms: 0` says the asker is
    /// in nothing, and `joined_rooms: 3` with no portals says it is in rooms
    /// and none of them is a conversation. One number turns a silence into a
    /// diagnosis.
    pub joined_rooms: Option<u64>,
}

/// The whole register at one instant: every portal room every readable bridge
/// holds, and what happened to the ones that could not be read.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Register {
    pub portals: Vec<Portal>,
    pub bridges: Vec<BridgeReading>,
}

impl Register {
    /// How many portals stand in each state. The fact the deployment has to
    /// be able to state: *the Sensor is outside 17 of your 18 conversations*.
    pub fn summary(&self) -> BTreeMap<Observation, u64> {
        let mut summary = BTreeMap::from([
            (Observation::Observing, 0),
            (Observation::Invited, 0),
            (Observation::Absent, 0),
            (Observation::Moved, 0),
        ]);
        for portal in &self.portals {
            *summary.entry(portal.observation).or_insert(0) += 1;
        }
        summary
    }

    pub fn unreadable_bridges(&self) -> u64 {
        self.bridges
            .iter()
            .filter(|bridge| bridge.unreadable.is_some())
            .count() as u64
    }
}

/// One bridge's read: its conversations, and how many rooms the account that
/// did the asking is in at all.
///
/// The second number exists because of #171: a bridge whose asker is joined to
/// nothing looks, in the portal list alone, exactly like a bridge that has
/// built no conversation yet.
struct BridgeRooms {
    portals: Vec<Portal>,
    joined_rooms: u64,
    /// Every room the bot is in, portal or not — what tells a successor the
    /// bridge has not marked yet from one it is not in at all.
    room_ids: Vec<String>,
}

/// What happened to one room of an observation request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ObservationOutcome {
    pub room_id: String,
    pub status: OutcomeStatus,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum OutcomeStatus {
    /// The Sensor was invited. It joins when it next syncs, provided
    /// `SENSOR_ALLOWED_INVITERS` names this bridge's bot.
    Invited,
    /// The Sensor was already in the room, or already invited to it.
    AlreadyObserved,
    /// The Sensor was removed from the room, so this conversation stops
    /// reaching the bus.
    Removed,
    /// The Sensor was not in the room to begin with.
    NotObserved,
    /// This room is not a portal of any bridge this Gateway can read. No call
    /// was made: the appservice credential acts only where its own bot
    /// already is, and a room id from a request is never a reason to use it
    /// somewhere else.
    UnknownPortal,
    /// The homeserver refused this one room. `reason` is its error code, or
    /// the Gateway's own.
    Failed { reason: String },
}

impl OutcomeStatus {
    pub fn label(&self) -> &'static str {
        match self {
            OutcomeStatus::Invited => "invited",
            OutcomeStatus::AlreadyObserved => "already_observed",
            OutcomeStatus::Removed => "removed",
            OutcomeStatus::NotObserved => "not_observed",
            OutcomeStatus::UnknownPortal => "unknown_portal",
            OutcomeStatus::Failed { .. } => "failed",
        }
    }
}

/// Why a whole request was refused, as opposed to one room of it failing.
#[derive(Debug)]
pub enum PortalRefusal {
    /// The request named more rooms than [`MAX_ROOMS_PER_REQUEST`], or named
    /// none.
    InvalidRequest { detail: String },
}

/// The register's configuration: where the homeserver is, who the Sensor is,
/// and one credential per bridge.
pub struct Portals {
    /// Base URL of the homeserver's **client** API, without a trailing slash.
    homeserver_url: String,
    /// The Matrix ID whose membership decides [`Observation`]
    /// (`GATEWAY_SENSOR_USER_ID`).
    sensor_user_id: String,
    /// Every bridge in `GATEWAY_BRIDGES`, in that order, with the appservice
    /// token that reads it or the reason there is none.
    bridges: Vec<PortalBridge>,
    /// `GATEWAY_CROWD_THRESHOLD`, or [`DEFAULT_CROWD_THRESHOLD`].
    crowd_threshold: u64,
    /// Where a conversation's move is journaled (issue #255). `None` when
    /// this deployment has no store — no consent configured — in which case
    /// a move is still decided and logged, and only the journal is missing.
    moves: Option<Arc<crate::store::Store>>,
    metrics: Arc<Metrics>,
    http: reqwest::Client,
}

/// One bridge, as the register sees it.
pub struct PortalBridge {
    pub bridge_id: String,
    pub network: String,
    /// The bridge's appservice token. `None` when the operator configured
    /// none, in which case that bridge's portals cannot be read at all.
    pub as_token: Option<String>,
    /// The bridge bot's Matrix ID (`GATEWAY_BRIDGE_<ID>_BOT_USER_ID`), which
    /// is the account every call about this bridge's portals is made **as**.
    ///
    /// `None` means the token's own identity does the asking, which is right
    /// for an ordinary access token and wrong for an appservice one — see
    /// [`Portals::asking_as`].
    pub bot_user_id: Option<String>,
}

impl Portals {
    /// `None` when this deployment cannot hold a register: no Sensor to
    /// invite, no homeserver to ask, or no bridge configured at all. The
    /// endpoints then answer `503` naming the variable, rather than an empty
    /// list — "this bridge has built no conversations yet" and "this Gateway
    /// cannot see your conversations" are very different claims.
    pub fn new(
        homeserver_url: Option<&str>,
        sensor_user_id: Option<&str>,
        bridges: Vec<PortalBridge>,
        crowd_threshold: u64,
        moves: Option<Arc<crate::store::Store>>,
        metrics: Arc<Metrics>,
    ) -> anyhow::Result<Option<Self>> {
        let (Some(homeserver_url), Some(sensor_user_id)) = (homeserver_url, sensor_user_id) else {
            return Ok(None);
        };
        if bridges.is_empty() {
            return Ok(None);
        }
        let http = reqwest::Client::builder()
            .timeout(HOMESERVER_TIMEOUT)
            .build()
            .map_err(|error| anyhow::anyhow!("{}", error.without_url()))?;
        Ok(Some(Self {
            homeserver_url: homeserver_url.trim_end_matches('/').to_owned(),
            sensor_user_id: sensor_user_id.to_owned(),
            bridges,
            crowd_threshold,
            moves,
            metrics,
            http,
        }))
    }

    /// The register's journal of moves, newest first; empty when this
    /// deployment keeps none.
    pub fn moves(&self, limit: usize) -> Vec<crate::store::PortalMove> {
        let Some(store) = &self.moves else {
            return Vec::new();
        };
        store.portal_moves(limit).unwrap_or_else(|error| {
            warn!(%error, "could not read the portal moves journal");
            Vec::new()
        })
    }

    /// Whether this deployment journals moves at all.
    pub fn journals_moves(&self) -> bool {
        self.moves.is_some()
    }

    /// The crowd threshold this deployment applies — see
    /// [`DEFAULT_CROWD_THRESHOLD`] for what it is and why it lives here.
    pub fn crowd_threshold(&self) -> u64 {
        self.crowd_threshold
    }

    pub fn sensor_user_id(&self) -> &str {
        &self.sensor_user_id
    }

    /// The account every call about one bridge's portals is made **as**.
    ///
    /// `Some(bot)` is the configured bridge bot, and becomes `?user_id=<bot>`
    /// on the request. `None` is the token's own identity, which is right for
    /// an ordinary access token — a test hands the register one — and wrong
    /// for an appservice token, where it is the registration's
    /// `sender_localpart` and is in no rooms (#171).
    ///
    /// This is the only place a masquerade is decided, and it can only ever
    /// return a value the operator wrote in configuration. Nothing derived
    /// from a request reaches it.
    fn asking_as(bridge: &PortalBridge) -> Option<&str> {
        bridge
            .bot_user_id
            .as_deref()
            .map(str::trim)
            .filter(|bot| !bot.is_empty())
    }

    /// Who the homeserver says this token is, when nothing is configured.
    ///
    /// One call per bridge per read, and only on the path where the operator
    /// named no bot. It exists so the answer can state the account it asked
    /// as: #171's defect was invisible precisely because the register could
    /// not say that, and a deployment could not tell "no conversations yet"
    /// from "asked an account that is in no rooms".
    async fn whoami(&self, as_token: &str) -> Result<String, String> {
        let url = self.url(&["_matrix", "client", "v3", "account", "whoami"], None)?;
        let response = self
            .http
            .get(url)
            .bearer_auth(as_token)
            .send()
            .await
            .map_err(|error| error.without_url().to_string())?;
        if !response.status().is_success() {
            return Err(matrix_error(response).await);
        }
        #[derive(Deserialize)]
        struct WhoAmI {
            user_id: String,
        }
        let who: WhoAmI = response
            .json()
            .await
            .map_err(|error| error.without_url().to_string())?;
        Ok(who.user_id)
    }

    /// Reads the whole register from the homeserver.
    ///
    /// One bridge failing never fails the read: it becomes a
    /// [`BridgeReading`] with the reason, and the portals of the bridges that
    /// answered are still returned. That is the point — a partial answer that
    /// says it is partial beats a refusal, and beats a total that silently
    /// counts fewer conversations than the user has.
    ///
    /// Updates the gauges as a side effect, so `/metrics` is as fresh as the
    /// last read whoever made it.
    pub async fn read(&self) -> Register {
        let mut register = Register::default();
        let mut bot_rooms: BTreeSet<String> = BTreeSet::new();
        for bridge in &self.bridges {
            let Some(as_token) = &bridge.as_token else {
                register.bridges.push(BridgeReading {
                    bridge_id: bridge.bridge_id.clone(),
                    network: bridge.network.clone(),
                    unreadable: Some(format!(
                        "no appservice token configured: set GATEWAY_BRIDGE_{}_AS_TOKEN to the \
                         same value as this bridge's own appservice.as_token",
                        crate::config::variable_slug(&bridge.bridge_id)
                    )),
                    asked_as: None,
                    joined_rooms: None,
                });
                continue;
            };
            // Who the asking is done as, resolved before anything is asked:
            // the configured bot, or — with none configured — whoever the
            // homeserver says this token is. Either way the answer states it,
            // which is the half of #171 that is not the fix but the reason
            // the fix took a production deployment to find.
            let asked_as = match Self::asking_as(bridge) {
                Some(bot) => Some(bot.to_owned()),
                None => self.whoami(as_token).await.ok(),
            };
            match self.read_bridge(bridge, as_token).await {
                Ok(reading) => {
                    if reading.joined_rooms == 0 {
                        // The exact symptom #171 was: a bridge that answers
                        // and is in nothing. True on a deployment whose
                        // bridges have built no portal yet, and a defect when
                        // the account is the appservice's sender_localpart —
                        // so the log names the account and the variable, and
                        // the answer carries both numbers.
                        warn!(
                            bridge = %bridge.bridge_id,
                            asked_as = asked_as.as_deref().unwrap_or("the token's own identity"),
                            variable = %format!(
                                "GATEWAY_BRIDGE_{}_BOT_USER_ID",
                                crate::config::variable_slug(&bridge.bridge_id)
                            ),
                            "the account the portal register asked as is joined to no rooms at \
                             all, so this bridge contributes no conversations: either it has \
                             built no portal yet, or this is the appservice's sender_localpart \
                             rather than the bridge's bot (#171)"
                        );
                    }
                    let mut portals = reading.portals;
                    register.portals.append(&mut portals);
                    bot_rooms.extend(reading.room_ids);
                    register.bridges.push(BridgeReading {
                        bridge_id: bridge.bridge_id.clone(),
                        network: bridge.network.clone(),
                        unreadable: None,
                        asked_as,
                        joined_rooms: Some(reading.joined_rooms),
                    });
                }
                Err(detail) => {
                    warn!(
                        bridge = %bridge.bridge_id,
                        %detail,
                        "could not read a bridge's portal rooms, so its conversations are not counted"
                    );
                    self.metrics.record_portal_refresh_failure();
                    register.bridges.push(BridgeReading {
                        bridge_id: bridge.bridge_id.clone(),
                        network: bridge.network.clone(),
                        unreadable: Some(detail),
                        asked_as,
                        joined_rooms: None,
                    });
                }
            }
        }
        register.portals = fold_tombstones(register.portals, &bot_rooms);
        self.decide_moves(&mut register.portals).await;
        // A stable order, so two reads of an unchanged deployment are the
        // same list: by bridge as configured, then by name, then by room id.
        let order: BTreeMap<&str, usize> = self
            .bridges
            .iter()
            .enumerate()
            .map(|(index, bridge)| (bridge.bridge_id.as_str(), index))
            .collect();
        register.portals.sort_by(|left, right| {
            order
                .get(left.bridge_id.as_str())
                .cmp(&order.get(right.bridge_id.as_str()))
                .then_with(|| left.name.cmp(&right.name))
                .then_with(|| left.room_id.cmp(&right.room_id))
        });
        self.metrics.set_portal_rooms(&register);
        register
    }

    /// Decides what the user's decision now means for every conversation
    /// whose room was replaced while the Sensor was in it (ADR 0029, issue
    /// #255) — the register decides, because "should this successor be
    /// followed?" is a consent question and consent has one writer.
    ///
    /// Under the crowd threshold the decision **follows the conversation**:
    /// the Sensor is invited into the successor as it would be on a tick,
    /// because the user decided about the conversation and not the room. At
    /// or above it the conversation stays `moved` and returns to the chooser
    /// as a crowd the user has to acknowledge again — a threshold that applied
    /// only at the moment of ticking would be one it suffices to wait out.
    /// **Either way the move is said**: journaled once, keyed on the
    /// successor, with the numbers it was decided on. A deployment that
    /// changed rooms under the user without being able to say so is one
    /// whose history they cannot check.
    ///
    /// A successor the register could not read is not decided: its count is
    /// the dead room's and would be the wrong number to hold a threshold
    /// against. It stays `moved`, which is already a sentence.
    async fn decide_moves(&self, portals: &mut [Portal]) {
        for portal in portals.iter_mut() {
            if portal.observation != Observation::Moved || portal.unreadable.is_some() {
                continue;
            }
            let Some(predecessor) = portal.moved_from.clone() else {
                continue;
            };
            let follow = portal.members < self.crowd_threshold;
            let first_decision = match &self.moves {
                Some(store) => match store.record_portal_move(&crate::store::PortalMove {
                    successor: portal.room_id.clone(),
                    predecessor: predecessor.clone(),
                    bridge_id: portal.bridge_id.clone(),
                    members: portal.members,
                    crowd_threshold: self.crowd_threshold,
                    followed: follow,
                    decided_at: crate::consent::rfc3339_millis(std::time::SystemTime::now()),
                }) {
                    Ok(recorded) => recorded,
                    Err(error) => {
                        warn!(%error, successor = %portal.room_id, "could not journal a move");
                        true
                    }
                },
                None => true,
            };
            if !follow {
                if first_decision {
                    warn!(
                        successor = %portal.room_id,
                        %predecessor,
                        members = portal.members,
                        crowd_threshold = self.crowd_threshold,
                        "a conversation the user observed moved to a room whose audience crosses \
                         the crowd threshold: not followed, returned to the chooser (ADR 0029)"
                    );
                }
                continue;
            }
            let Some(bridge) = self
                .bridges
                .iter()
                .find(|bridge| bridge.bridge_id == portal.bridge_id)
            else {
                continue;
            };
            let Some(as_token) = &bridge.as_token else {
                continue;
            };
            match self.invite(as_token, Self::asking_as(bridge), portal).await {
                OutcomeStatus::Invited | OutcomeStatus::AlreadyObserved => {
                    portal.observation = Observation::Invited;
                    info!(
                        successor = %portal.room_id,
                        %predecessor,
                        members = portal.members,
                        crowd_threshold = self.crowd_threshold,
                        "a conversation the user observed moved: the decision followed it, the \
                         Sensor is invited into the new room (ADR 0029)"
                    );
                }
                other => warn!(
                    successor = %portal.room_id,
                    %predecessor,
                    outcome = other.label(),
                    "a conversation the user observed moved and the Sensor could not be invited \
                     into the new room; it stays reported as moved"
                ),
            }
        }
    }

    /// One bridge's portal rooms, read as its own bot.
    async fn read_bridge(
        &self,
        bridge: &PortalBridge,
        as_token: &str,
    ) -> Result<BridgeRooms, String> {
        let rooms = self.joined_rooms(as_token, Self::asking_as(bridge)).await?;
        let joined_rooms = rooms.len() as u64;
        let portals: Vec<Option<Portal>> = futures::stream::iter(rooms.clone())
            .map(|room_id| async move {
                match self.portal_of(bridge, as_token, &room_id).await {
                    Ok(portal) => portal,
                    Err(detail) => {
                        // One unreadable room is not a reason to lose the
                        // other seventeen; it is a reason to say so.
                        warn!(
                            bridge = %bridge.bridge_id,
                            room = %room_id,
                            %detail,
                            "could not read a room the bridge bot is in, skipping it"
                        );
                        None
                    }
                }
            })
            .buffer_unordered(ROOM_READ_CONCURRENCY)
            .collect()
            .await;
        Ok(BridgeRooms {
            portals: portals.into_iter().flatten().collect(),
            joined_rooms,
            room_ids: rooms,
        })
    }

    /// The rooms the asking account is joined to — **all** of them, not only
    /// the conversations, because the count of rooms that are not portals is
    /// what tells an asker in no rooms from a bridge with no portals yet.
    async fn joined_rooms(
        &self,
        as_token: &str,
        asking_as: Option<&str>,
    ) -> Result<Vec<String>, String> {
        let url = self.url(&["_matrix", "client", "v3", "joined_rooms"], asking_as)?;
        let response = self
            .http
            .get(url)
            .bearer_auth(as_token)
            .send()
            .await
            .map_err(|error| error.without_url().to_string())?;
        if !response.status().is_success() {
            return Err(matrix_error(response).await);
        }
        #[derive(Deserialize)]
        struct JoinedRooms {
            #[serde(default)]
            joined_rooms: Vec<String>,
        }
        let joined: JoinedRooms = response
            .json()
            .await
            .map_err(|error| error.without_url().to_string())?;
        Ok(joined.joined_rooms)
    }

    /// One room: a portal of this bridge, or not one at all.
    ///
    /// The marker is the room's `m.bridge` state event — the same one the
    /// Sensor attributes a network with (`sensor/src/network.rs`), so a room
    /// this register offers is a room the Sensor could publish. A room the
    /// bot is in that carries no marker is the bridge's management room or
    /// its space, and is not a conversation.
    async fn portal_of(
        &self,
        bridge: &PortalBridge,
        as_token: &str,
        room_id: &str,
    ) -> Result<Option<Portal>, String> {
        let url = self.url(
            &["_matrix", "client", "v3", "rooms", room_id, "state"],
            Self::asking_as(bridge),
        )?;
        let response = self
            .http
            .get(url)
            .bearer_auth(as_token)
            .send()
            .await
            .map_err(|error| error.without_url().to_string())?;
        if !response.status().is_success() {
            return Err(matrix_error(response).await);
        }
        let state: Vec<serde_json::Value> = response
            .json()
            .await
            .map_err(|error| error.without_url().to_string())?;

        let mut bridged = false;
        let mut network = None;
        let mut conversation = None;
        let mut name = None;
        let mut members = 0u64;
        let mut observation = Observation::Absent;
        let mut replaced_by = None;
        let mut moved_from = None;
        let bot = bot_user_id(&state);
        for event in &state {
            let Some(event_type) = event.get("type").and_then(serde_json::Value::as_str) else {
                continue;
            };
            let content = event.get("content");
            match event_type {
                "m.bridge" => {
                    bridged = true;
                    network = network.or_else(|| {
                        content
                            .and_then(|content| content.get("protocol"))
                            .and_then(|protocol| protocol.get("id"))
                            .and_then(serde_json::Value::as_str)
                            .and_then(network_of_protocol)
                            .map(str::to_owned)
                    });
                    // The network's own id for this conversation, copied and
                    // not read: the suffix that says one-to-one from group is
                    // the Companion's to parse (#143). An empty string is a
                    // bridge that wrote the field and said nothing, which is
                    // the same as not writing it.
                    conversation = conversation.or_else(|| {
                        content
                            .and_then(|content| content.get("channel"))
                            .and_then(|channel| channel.get("id"))
                            .and_then(serde_json::Value::as_str)
                            .filter(|id| !id.is_empty())
                            .map(str::to_owned)
                    });
                }
                // ADR 0029: the tombstone names the successor, the successor's
                // create event names the predecessor. Both are the homeserver's
                // own facts about the chain, read here and folded afterwards.
                "m.room.tombstone" => {
                    replaced_by = content
                        .and_then(|content| content.get("replacement_room"))
                        .and_then(serde_json::Value::as_str)
                        .filter(|room| !room.is_empty())
                        .map(str::to_owned);
                }
                "m.room.create" => {
                    moved_from = content
                        .and_then(|content| content.get("predecessor"))
                        .and_then(|predecessor| predecessor.get("room_id"))
                        .and_then(serde_json::Value::as_str)
                        .filter(|room| !room.is_empty())
                        .map(str::to_owned);
                }
                "m.room.name" => {
                    name = content
                        .and_then(|content| content.get("name"))
                        .and_then(serde_json::Value::as_str)
                        .filter(|name| !name.is_empty())
                        .map(str::to_owned);
                }
                "m.room.member" => {
                    let Some(who) = event.get("state_key").and_then(serde_json::Value::as_str)
                    else {
                        continue;
                    };
                    let membership = content
                        .and_then(|content| content.get("membership"))
                        .and_then(serde_json::Value::as_str)
                        .unwrap_or_default();
                    if who == self.sensor_user_id {
                        observation = match membership {
                            "join" => Observation::Observing,
                            "invite" => Observation::Invited,
                            _ => Observation::Absent,
                        };
                        continue;
                    }
                    if membership != "join" {
                        continue;
                    }
                    // The bridge bot is the account doing the asking, so it
                    // is in every one of these rooms and is nobody's
                    // correspondent. Counting it would make every
                    // conversation look one person larger than it is.
                    //
                    // Two spellings of the same account, and both are
                    // excluded: the one the room's own marker names
                    // (`bridgebot`) and the one the operator configured as the
                    // asker. They normally agree; where they do not, the room
                    // is the authority on who its bot is and the configured
                    // value is the authority on who we are.
                    if Some(who) == bot.as_deref() || Some(who) == Self::asking_as(bridge) {
                        continue;
                    }
                    members += 1;
                }
                _ => {}
            }
        }
        if !bridged {
            debug!(
                bridge = %bridge.bridge_id,
                room = %room_id,
                "a room with no m.bridge marker is not a conversation, skipping it"
            );
            return Ok(None);
        }
        Ok(Some(Portal {
            room_id: room_id.to_owned(),
            bridge_id: bridge.bridge_id.clone(),
            network: network.unwrap_or_else(|| bridge.network.clone()),
            name,
            network_conversation_id: conversation,
            members,
            observation,
            moved_from,
            unreadable: None,
            replaced_by,
        }))
    }

    /// Puts the Sensor into the named portal rooms, or takes it out of them.
    ///
    /// Every room is resolved against a live register first. A room this
    /// Gateway does not hold as a portal is answered
    /// [`OutcomeStatus::UnknownPortal`] and **no call is made with the
    /// appservice credential** — that credential's reach is the bot's own
    /// rooms and a room id in a request is never a reason to widen it.
    pub async fn set_observation(
        &self,
        rooms: &[String],
        observed: bool,
    ) -> Result<Vec<ObservationOutcome>, PortalRefusal> {
        if rooms.is_empty() {
            return Err(PortalRefusal::InvalidRequest {
                detail: "name at least one room".to_owned(),
            });
        }
        if rooms.len() > MAX_ROOMS_PER_REQUEST {
            return Err(PortalRefusal::InvalidRequest {
                detail: format!(
                    "too many rooms in one request: {} named, {MAX_ROOMS_PER_REQUEST} is the most",
                    rooms.len()
                ),
            });
        }
        let register = self.read().await;
        let known: BTreeMap<&str, &Portal> = register
            .portals
            .iter()
            .map(|portal| (portal.room_id.as_str(), portal))
            .collect();
        // The bridge itself, not only its token: acting on a portal takes the
        // credential **and** the account to act as, and separating them is
        // what let #171 read as one identity while documenting another.
        let askers: BTreeMap<&str, (&str, Option<&str>)> = self
            .bridges
            .iter()
            .filter_map(|bridge| {
                Some((
                    bridge.bridge_id.as_str(),
                    (bridge.as_token.as_deref()?, Self::asking_as(bridge)),
                ))
            })
            .collect();

        let mut outcomes = Vec::with_capacity(rooms.len());
        for room_id in rooms {
            let Some(portal) = known.get(room_id.as_str()) else {
                outcomes.push(ObservationOutcome {
                    room_id: room_id.clone(),
                    status: OutcomeStatus::UnknownPortal,
                });
                continue;
            };
            let Some((as_token, asking_as)) = askers.get(portal.bridge_id.as_str()).copied() else {
                // Unreachable in practice: a portal is only in the register
                // because its bridge's token read it.
                outcomes.push(ObservationOutcome {
                    room_id: room_id.clone(),
                    status: OutcomeStatus::Failed {
                        reason: "no_appservice_token".to_owned(),
                    },
                });
                continue;
            };
            let status = if observed {
                self.invite(as_token, asking_as, portal).await
            } else {
                self.remove(as_token, asking_as, portal).await
            };
            outcomes.push(ObservationOutcome {
                room_id: room_id.clone(),
                status,
            });
        }
        Ok(outcomes)
    }

    /// Invites the Sensor into one portal, as the bridge's own bot.
    async fn invite(
        &self,
        as_token: &str,
        asking_as: Option<&str>,
        portal: &Portal,
    ) -> OutcomeStatus {
        // `moved` is a room the Sensor is not in either: ticking a moved
        // conversation is the user re-deciding it at its successor, which is
        // exactly the decision ADR 0029 returns to them above the threshold.
        if portal.observation.sensor_is_in_the_room() {
            return OutcomeStatus::AlreadyObserved;
        }
        let url = match self.url(
            &[
                "_matrix",
                "client",
                "v3",
                "rooms",
                &portal.room_id,
                "invite",
            ],
            asking_as,
        ) {
            Ok(url) => url,
            Err(detail) => return OutcomeStatus::Failed { reason: detail },
        };
        let response = self
            .http
            .post(url)
            .bearer_auth(as_token)
            .json(&serde_json::json!({ "user_id": self.sensor_user_id }))
            .send()
            .await;
        match response {
            Ok(response) if response.status().is_success() => {
                info!(
                    room = %portal.room_id,
                    bridge = %portal.bridge_id,
                    sensor = %self.sensor_user_id,
                    "invited the Sensor into a portal room"
                );
                OutcomeStatus::Invited
            }
            Ok(response) => {
                let detail = matrix_error(response).await;
                if detail.contains("already in the room") {
                    return OutcomeStatus::AlreadyObserved;
                }
                warn!(
                    room = %portal.room_id,
                    %detail,
                    "the homeserver refused to invite the Sensor into a portal room"
                );
                OutcomeStatus::Failed {
                    reason: errcode_of(&detail),
                }
            }
            Err(error) => OutcomeStatus::Failed {
                reason: error.without_url().to_string(),
            },
        }
    }

    /// Takes the Sensor out of one portal, as the bridge's own bot.
    ///
    /// A removal rather than a request to leave: the Sensor has no inbound
    /// API and inventing one so that it could be asked to leave a room would
    /// be a second control plane for a membership Matrix already models. The
    /// bot created the room and can remove a member from it, so stopping
    /// observation is the exact inverse of starting it, through one
    /// credential and one mechanism.
    async fn remove(
        &self,
        as_token: &str,
        asking_as: Option<&str>,
        portal: &Portal,
    ) -> OutcomeStatus {
        if !portal.observation.sensor_is_in_the_room() {
            return OutcomeStatus::NotObserved;
        }
        let url = match self.url(
            &["_matrix", "client", "v3", "rooms", &portal.room_id, "kick"],
            asking_as,
        ) {
            Ok(url) => url,
            Err(detail) => return OutcomeStatus::Failed { reason: detail },
        };
        let response = self
            .http
            .post(url)
            .bearer_auth(as_token)
            .json(&serde_json::json!({
                "user_id": self.sensor_user_id,
                "reason": "the user stopped observing this conversation",
            }))
            .send()
            .await;
        match response {
            Ok(response) if response.status().is_success() => {
                info!(
                    room = %portal.room_id,
                    bridge = %portal.bridge_id,
                    sensor = %self.sensor_user_id,
                    "removed the Sensor from a portal room"
                );
                OutcomeStatus::Removed
            }
            Ok(response) => {
                let detail = matrix_error(response).await;
                warn!(
                    room = %portal.room_id,
                    %detail,
                    "the homeserver refused to remove the Sensor from a portal room"
                );
                OutcomeStatus::Failed {
                    reason: errcode_of(&detail),
                }
            }
            Err(error) => OutcomeStatus::Failed {
                reason: error.without_url().to_string(),
            },
        }
    }

    /// Joins a path onto the homeserver's base URL, percent-encoding each
    /// segment — room ids carry `!` and `:` — and adds the masquerade.
    ///
    /// `asking_as` is threaded through every call rather than applied at some
    /// of them: the register's four homeserver calls (the room list, one room's
    /// state, the invitation, the removal) all have to be made as the same
    /// account, and #171 is what one of them not being is worth. Making it a
    /// parameter of the URL builder is how a fifth call cannot forget it.
    fn url(&self, segments: &[&str], asking_as: Option<&str>) -> Result<reqwest::Url, String> {
        let mut url = reqwest::Url::parse(&self.homeserver_url)
            .map_err(|error| format!("GATEWAY_HOMESERVER_URL is not a URL: {error}"))?;
        url.path_segments_mut()
            .map_err(|_| "GATEWAY_HOMESERVER_URL cannot carry a path".to_owned())?
            .pop_if_empty()
            .extend(segments);
        if let Some(bot) = asking_as {
            url.query_pairs_mut().append_pair("user_id", bot);
        }
        Ok(url)
    }
}

/// Re-reads the register on an interval, for as long as the process runs, so
/// `/metrics` can state how many conversations the Sensor is outside without
/// anybody opening the Companion.
///
/// This is the loop that makes the mechanism *continuous*. The bridge builds
/// a portal when a conversation becomes active, and there is no push the
/// Gateway could subscribe to — an appservice transaction goes to the
/// appservice, and the appservice is the bridge. So the register is read
/// again, and a portal created at 13:24 is in it by 13:29 at the latest, and
/// in the Companion's own read immediately.
pub async fn refresh_until_shutdown(portals: Arc<Portals>, interval_seconds: u64) {
    if interval_seconds == 0 {
        info!("the portal register's background refresh is off (GATEWAY_PORTAL_REFRESH_SECONDS=0)");
        return;
    }
    let interval = std::time::Duration::from_secs(interval_seconds);
    info!(
        seconds = interval_seconds,
        sensor = %portals.sensor_user_id(),
        "refreshing the portal register"
    );
    loop {
        let register = portals.read().await;
        let summary = register.summary();
        debug!(
            observing = summary
                .get(&Observation::Observing)
                .copied()
                .unwrap_or_default(),
            invited = summary
                .get(&Observation::Invited)
                .copied()
                .unwrap_or_default(),
            absent = summary
                .get(&Observation::Absent)
                .copied()
                .unwrap_or_default(),
            moved = summary
                .get(&Observation::Moved)
                .copied()
                .unwrap_or_default(),
            unreadable_bridges = register.unreadable_bridges(),
            "read the portal register"
        );
        tokio::time::sleep(interval).await;
    }
}

/// The bridge bot's own Matrix ID, read out of the room's state rather than
/// asked for: the `m.bridge` marker names it in `content.bridgebot`, which
/// saves a `whoami` per bridge and stays right on a deployment running two.
/// `None` when the marker omits it, in which case the bot is counted as a
/// member — a conversation one person too large is a better failure than a
/// count that silently drops somebody.
fn bot_user_id(state: &[serde_json::Value]) -> Option<String> {
    state
        .iter()
        .filter(|event| event.get("type").and_then(serde_json::Value::as_str) == Some("m.bridge"))
        .find_map(|event| {
            event
                .get("content")?
                .get("bridgebot")?
                .as_str()
                .map(str::to_owned)
        })
}

/// The contract network a bridge's `m.bridge` protocol id names, or `None`
/// when this version knows none — the same folding the Sensor does
/// (`sensor/src/network.rs`), so the two cannot disagree about a room.
fn network_of_protocol(protocol_id: &str) -> Option<&'static str> {
    match protocol_id {
        "whatsapp" => Some("whatsapp"),
        "telegram" => Some("telegram"),
        "signal" => Some("signal"),
        "discord" | "discordgo" => Some("discord"),
        "sms" | "gmessages" | "gmessages-sms" | "gmessages-rcs" => Some("sms"),
        _ => None,
    }
}

/// The homeserver's own words about a refusal: its error code and message,
/// for the operator's log and for the `reason` one room carries.
async fn matrix_error(response: reqwest::Response) -> String {
    let status = response.status();
    let body = response.text().await.unwrap_or_default();
    match serde_json::from_str::<serde_json::Value>(&body) {
        Ok(document) => {
            let errcode = document
                .get("errcode")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("unknown");
            let error = document
                .get("error")
                .and_then(serde_json::Value::as_str)
                .unwrap_or_default();
            format!("{status}: {errcode} {error}").trim_end().to_owned()
        }
        Err(_) => format!("{status}"),
    }
}

/// The `M_...` code out of [`matrix_error`]'s sentence, which is the part a
/// client can act on. A closed shape, so a `reason` never carries a
/// homeserver's prose.
fn errcode_of(detail: &str) -> String {
    detail
        .split_whitespace()
        .find(|word| word.starts_with("M_"))
        .unwrap_or("unreachable")
        .to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn portal(room_id: &str, observation: Observation) -> Portal {
        Portal {
            room_id: room_id.to_owned(),
            bridge_id: "mautrix-whatsapp".to_owned(),
            network: "whatsapp".to_owned(),
            name: None,
            network_conversation_id: None,
            members: 2,
            observation,
            moved_from: None,
            unreadable: None,
            replaced_by: None,
        }
    }

    fn replaced(room_id: &str, observation: Observation, by: &str) -> Portal {
        Portal {
            replaced_by: Some(by.to_owned()),
            ..portal(room_id, observation)
        }
    }

    fn successor_of(room_id: &str, observation: Observation, predecessor: &str) -> Portal {
        Portal {
            moved_from: Some(predecessor.to_owned()),
            ..portal(room_id, observation)
        }
    }

    fn row<'a>(rows: &'a [Portal], room_id: &str) -> &'a Portal {
        rows.iter()
            .find(|row| row.room_id == room_id)
            .unwrap_or_else(|| panic!("no row for {room_id} in {rows:?}"))
    }

    #[test]
    fn a_replaced_room_is_folded_onto_its_successor_once() {
        // ADR 0029: the dead room is not a row; the successor says where it
        // came from; and the Sensor's presence in the dead room is what makes
        // the successor `moved` rather than `absent`.
        let rows = fold_tombstones(
            vec![
                replaced("!old:x", Observation::Observing, "!new:x"),
                successor_of("!new:x", Observation::Absent, "!old:x"),
                replaced("!ignored-old:x", Observation::Absent, "!ignored-new:x"),
                successor_of("!ignored-new:x", Observation::Absent, "!ignored-old:x"),
                portal("!untouched:x", Observation::Observing),
            ],
            &BTreeSet::new(),
        );
        assert_eq!(rows.len(), 3, "{rows:?}");
        assert_eq!(row(&rows, "!new:x").observation, Observation::Moved);
        assert_eq!(row(&rows, "!new:x").moved_from.as_deref(), Some("!old:x"));
        assert_eq!(
            row(&rows, "!ignored-new:x").observation,
            Observation::Absent,
            "a conversation nobody chose moves and stays absent"
        );
        assert_eq!(
            row(&rows, "!untouched:x").observation,
            Observation::Observing
        );
        assert!(rows.iter().all(|row| row.unreadable.is_none()));
    }

    #[test]
    fn a_successor_the_sensor_already_joined_is_observing_not_moved() {
        // The register invited the Sensor to the successor (#255) and it
        // joined: the live room knows better than the dead one.
        let rows = fold_tombstones(
            vec![
                replaced("!old:x", Observation::Observing, "!new:x"),
                successor_of("!new:x", Observation::Observing, "!old:x"),
            ],
            &BTreeSet::new(),
        );
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].observation, Observation::Observing);
        assert_eq!(rows[0].moved_from.as_deref(), Some("!old:x"));
    }

    #[test]
    fn a_chain_ends_at_its_last_room_and_names_the_immediate_predecessor() {
        let rows = fold_tombstones(
            vec![
                replaced("!a:x", Observation::Observing, "!b:x"),
                replaced("!b:x", Observation::Absent, "!c:x"),
                successor_of("!c:x", Observation::Absent, "!b:x"),
            ],
            &BTreeSet::new(),
        );
        assert_eq!(rows.len(), 1, "{rows:?}");
        assert_eq!(rows[0].room_id, "!c:x");
        assert_eq!(
            rows[0].observation,
            Observation::Moved,
            "the Sensor was in !a"
        );
        assert_eq!(rows[0].moved_from.as_deref(), Some("!b:x"));
    }

    #[test]
    fn a_successor_in_the_dark_is_a_row_built_from_the_tombstone() {
        let mut dead = replaced("!old:x", Observation::Observing, "!dark:x");
        dead.name = Some("Maria".to_owned());
        let rows = fold_tombstones(vec![dead], &BTreeSet::new());
        assert_eq!(rows.len(), 1, "{rows:?}");
        let named = &rows[0];
        assert_eq!(named.room_id, "!dark:x");
        assert_eq!(named.observation, Observation::Moved);
        assert_eq!(named.moved_from.as_deref(), Some("!old:x"));
        assert_eq!(
            named.name.as_deref(),
            Some("Maria"),
            "what the old room knew is kept"
        );
        assert!(
            named.unreadable.is_some(),
            "and the row says it could not be read"
        );
        assert!(
            named.replaced_by.is_none(),
            "the row is the live end of the chain"
        );
    }

    #[test]
    fn a_successor_the_bot_is_in_but_has_not_marked_yet_says_so() {
        // The ordinary window right after a migration: a room upgrade copies
        // no custom state, so the successor has no m.bridge until the bridge
        // writes one. The bot is in it; the reason must say that, not "not in
        // the room".
        let rows = fold_tombstones(
            vec![replaced("!old:x", Observation::Observing, "!new:x")],
            &BTreeSet::from(["!new:x".to_owned()]),
        );
        let why = rows[0].unreadable.as_deref().expect("unreadable");
        assert!(why.contains("has not marked it as a portal yet"), "{why}");
        let rows = fold_tombstones(
            vec![replaced("!old:x", Observation::Observing, "!dark:x")],
            &BTreeSet::new(),
        );
        let why = rows[0].unreadable.as_deref().expect("unreadable");
        assert!(why.contains("is not in the new room"), "{why}");
    }

    #[test]
    fn two_dead_rooms_naming_one_successor_fold_deterministically_and_keep_the_decision() {
        let rows = fold_tombstones(
            vec![
                replaced("!b-old:x", Observation::Absent, "!new:x"),
                replaced("!a-old:x", Observation::Invited, "!new:x"),
                successor_of("!new:x", Observation::Absent, "!a-old:x"),
            ],
            &BTreeSet::new(),
        );
        assert_eq!(rows.len(), 1, "{rows:?}");
        assert_eq!(
            rows[0].observation,
            Observation::Moved,
            "an invitation is a decision on record"
        );
        assert_eq!(
            rows[0].moved_from.as_deref(),
            Some("!a-old:x"),
            "the successor's own predecessor wins"
        );
    }

    #[test]
    fn a_cycle_a_misbehaving_server_produced_does_not_spin_for_ever() {
        let rows = fold_tombstones(
            vec![
                replaced("!a:x", Observation::Observing, "!b:x"),
                replaced("!b:x", Observation::Absent, "!a:x"),
            ],
            &BTreeSet::new(),
        );
        assert!(!rows.is_empty(), "the chain ends somewhere: {rows:?}");
    }

    #[test]
    fn the_summary_counts_every_state_even_at_zero() {
        // A deployment that observes nothing must be able to say so, which
        // means the series exists at zero rather than being absent.
        let register = Register::default();
        let summary = register.summary();
        assert_eq!(summary.get(&Observation::Observing), Some(&0));
        assert_eq!(summary.get(&Observation::Invited), Some(&0));
        assert_eq!(summary.get(&Observation::Absent), Some(&0));
    }

    #[test]
    fn the_summary_is_the_sentence_the_deployment_has_to_be_able_to_say() {
        let mut register = Register::default();
        register
            .portals
            .push(portal("!a:x", Observation::Observing));
        for index in 0..17 {
            register
                .portals
                .push(portal(&format!("!b{index}:x"), Observation::Absent));
        }
        let summary = register.summary();
        assert_eq!(summary.get(&Observation::Observing), Some(&1));
        assert_eq!(summary.get(&Observation::Absent), Some(&17));
        assert_eq!(register.portals.len(), 18);
    }

    #[test]
    fn a_bridge_with_no_token_is_reported_not_skipped() {
        let register = Register {
            portals: Vec::new(),
            bridges: vec![
                BridgeReading {
                    bridge_id: "mautrix-whatsapp".to_owned(),
                    network: "whatsapp".to_owned(),
                    unreadable: None,
                    asked_as: Some("@whatsappbot:example.com".to_owned()),
                    joined_rooms: Some(20),
                },
                BridgeReading {
                    bridge_id: "mautrix-signal".to_owned(),
                    network: "signal".to_owned(),
                    unreadable: Some("no appservice token configured".to_owned()),
                    asked_as: None,
                    joined_rooms: None,
                },
            ],
        };
        assert_eq!(register.unreadable_bridges(), 1);
    }

    fn bridge(bot_user_id: Option<&str>) -> PortalBridge {
        PortalBridge {
            bridge_id: "mautrix-whatsapp".to_owned(),
            network: "whatsapp".to_owned(),
            as_token: Some("test-only-as-token".to_owned()),
            bot_user_id: bot_user_id.map(str::to_owned),
        }
    }

    /// The masquerade can only ever name the configured bot (#171).
    #[test]
    fn the_only_account_the_register_ever_acts_as_is_the_configured_bot() {
        assert_eq!(
            Portals::asking_as(&bridge(Some("@whatsappbot:example.com"))),
            Some("@whatsappbot:example.com")
        );
        // Nothing configured: the token's own identity asks, which is right
        // for an ordinary access token and is what the suite's fixtures use.
        assert_eq!(Portals::asking_as(&bridge(None)), None);
        // A variable set to whitespace is a variable the operator meant to
        // set and did not. Sending `?user_id=` with nothing in it would be a
        // 400 from the homeserver on every call.
        assert_eq!(Portals::asking_as(&bridge(Some("   "))), None);
    }

    #[test]
    fn a_protocol_id_folds_to_the_network_the_sensor_would_attribute() {
        assert_eq!(network_of_protocol("whatsapp"), Some("whatsapp"));
        assert_eq!(network_of_protocol("gmessages-rcs"), Some("sms"));
        assert_eq!(network_of_protocol("discordgo"), Some("discord"));
        // Unknown means the Sensor could not attribute it either; the
        // bridge's configured network is the fallback, never a guess here.
        assert_eq!(network_of_protocol("matrix"), None);
        assert_eq!(network_of_protocol("irc"), None);
    }

    #[test]
    fn a_reason_is_an_error_code_and_never_the_homeservers_prose() {
        assert_eq!(
            errcode_of("403 Forbidden: M_FORBIDDEN @sensor:x is not invited to this room"),
            "M_FORBIDDEN"
        );
        assert_eq!(errcode_of("502 Bad Gateway"), "unreachable");
    }
}
